# Generated by Django 5.1.5 on 2025-01-22 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="participants",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
